name = "wokerd1-blue-math-ewq"
main = "src/src/index.js"
compatibility_date = "2023-08-23"
workers_dev = true

[[d1_databases]]
binding = "DATABASE"
database_id = "50fd8735-d3af-4211-b3ce-9d597709dbea"
database_name = "wokerd1-blue-math-ewq-db"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.